language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: "sh test.sh"
notifications:
  irc:
    channels:
      - "irc.freenode.org#sacl2"
      - "irc.freenode.org#itayo"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
